export function localRoomHtml(): string {
	return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>MultiCodex local alpha</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#17211b;background:#eef1ec}*{box-sizing:border-box}body{margin:0}.top{height:68px;background:#17211b;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 24px}.brand{font-weight:850;font-size:20px}.brand b{color:#f2c84b}.live{font-size:12px;color:#b7d7c4}.shell{display:grid;grid-template-columns:280px minmax(0,1fr) 340px;min-height:calc(100vh - 68px)}aside,main,.right{padding:18px;border-right:1px solid #ccd4cc}.eyebrow{font-size:11px;text-transform:uppercase;color:#607067;font-weight:800}h1,h2,p{margin:0}h1{font-size:20px;margin-top:5px}h2{font-size:15px;margin:18px 0 12px}.lane{background:#fff;border:1px solid #ccd4cc;border-left:4px solid #2c7a58;padding:12px;margin:10px 0;border-radius:6px}.lane.off{border-left-color:#aeb6af}.lane strong,.lane span{display:block}.lane span{font-size:12px;color:#637068;margin-top:3px}.policy{display:inline-block!important;background:#e5efe8;color:#276044!important;padding:2px 6px;border-radius:4px;margin-top:8px!important}main{background:#f8faf7}.event{display:grid;grid-template-columns:minmax(145px,165px) minmax(0,1fr) 72px;gap:12px;padding:12px 0;border-bottom:1px solid #dde3dd}.event code{font-size:11px;color:#276044;line-height:1.35;overflow-wrap:anywhere}.event strong{font-size:13px;line-height:1.4}.event time{font-size:11px;color:#748078;text-align:right}.empty{padding:30px 0;color:#718078}.message{background:#fff;border:1px solid #ccd4cc;padding:10px;margin:8px 0;border-radius:6px}.message strong{font-size:11px;color:#276044;text-transform:uppercase}.message p{font-size:13px;margin-top:4px;white-space:pre-wrap}form{display:grid;gap:8px;margin:16px 0;padding-top:16px;border-top:1px solid #ccd4cc}input,select,button{font:inherit;border-radius:5px;border:1px solid #b9c4bb;padding:9px;background:#fff}button{background:#17211b;color:#fff;border-color:#17211b;font-weight:750;cursor:pointer}.status{font-size:12px;color:#617068;margin-top:8px}@media(max-width:980px){.shell{grid-template-columns:1fr}.shell>*{border-right:0;border-bottom:1px solid #ccd4cc}.event{grid-template-columns:minmax(125px,145px) minmax(0,1fr)}.event time{display:none}}
</style></head><body>
<header class="top"><div class="brand">multi<b>codex</b> / local alpha</div><div class="live">host-local conductor + local Codex lanes</div></header>
<div class="shell"><aside><div class="eyebrow">room</div><h1 id="title">loading</h1><p class="status" id="repo"></p><h2>builder lanes</h2><div id="lanes"></div></aside>
<main><div class="eyebrow">structured activity</div><h1>live lane events</h1><div id="events"></div></main>
<section class="right"><div class="eyebrow">conductor</div><h1>host-local control</h1><div id="messages"></div>
<form id="message-form"><input name="text" placeholder="message the conductor" required><button>send to conductor</button></form>
<form id="steer-form"><select name="laneId" id="lane-select" required></select><input name="text" placeholder="visible steer for active turn" required><button>ask conductor to steer</button></form>
<p class="status" id="status">connecting...</p></section></div>
<script>
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ui={title:document.querySelector('#title'),repo:document.querySelector('#repo'),lanes:document.querySelector('#lanes'),events:document.querySelector('#events'),messages:document.querySelector('#messages'),laneSelect:document.querySelector('#lane-select'),status:document.querySelector('#status')};
async function api(p,b){const r=await fetch(p,{method:b?'POST':'GET',headers:b?{'content-type':'application/json'}:{},body:b?JSON.stringify(b):undefined});if(!r.ok)throw new Error((await r.json()).error||r.statusText);return r.json()}
async function refresh(){try{const s=await api('/api/snapshot');ui.title.textContent=s.title;ui.repo.textContent=s.repo+' · '+s.id;ui.lanes.innerHTML=s.lanes.length?s.lanes.map(l=>'<div class="lane '+(l.connected?'':'off')+'"><strong>'+esc(l.displayName)+'</strong><span>'+esc(l.status)+'</span><span>'+esc(l.threadId||'thread pending')+'</span><span class="policy">'+l.policy+'</span></div>').join(''):'<p class="empty">run the printed join command</p>';laneSelect(s.lanes);ui.events.innerHTML=s.events.length?s.events.slice().reverse().map(e=>'<div class="event"><code>'+e.kind+'</code><strong>'+esc(e.summary)+'</strong><time>'+new Date(e.at).toLocaleTimeString()+'</time></div>').join(''):'<p class="empty">waiting for Codex activity</p>';ui.messages.innerHTML=s.conductorMessages.length?s.conductorMessages.slice().reverse().map(m=>'<div class="message"><strong>'+m.author+'</strong><p>'+esc(m.body)+'</p></div>').join(''):'<p class="empty">message the conductor to start</p>';ui.status.textContent='live · '+new Date().toLocaleTimeString()}catch(e){ui.status.textContent=e.message}}
function laneSelect(ls){const x=ui.laneSelect,v=x.value;x.innerHTML=ls.map(l=>'<option value="'+l.id+'">'+esc(l.displayName)+'</option>').join('');x.value=v}
document.querySelector('#message-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api('/api/conductor/message',{text:f.get('text')});e.target.reset();refresh()}
document.querySelector('#steer-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api('/api/conductor/steer',{laneId:f.get('laneId'),text:f.get('text')});e.target.querySelector('input').value='';refresh()}
setInterval(refresh,900);refresh();
</script></body></html>`;
}
