import { GHOSTTY_ASSET_PATHS } from "@openclaw/libterminal/node";

export function localRoomHtml(): string {
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MultiCodex control room</title>
  <style>
    :root{font-family:"Avenir Next","Segoe UI",sans-serif;color:#18211d;background:#e9ede8;--paper:#fbfcf8;--soft:#eef2ec;--line:#d4dbd4;--ink-soft:#65716b;--red:#dd503c;--green:#16825d;--blue:#3267d6;--yellow:#d59b18;--terminal:#171d1a;--terminal-line:#2c3731;--terminal-copy:#d9e4dc}
    *{box-sizing:border-box}body{margin:0;min-width:320px;min-height:100vh;overflow-x:hidden}button,input,select,textarea{font:inherit;letter-spacing:0}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.42}[hidden]{display:none!important}h1,h2,p{margin:0}.mono,.eyebrow,.status,.event-time,.event-kind,.policy,.terminal-meta{font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace}
    .topbar{align-items:center;background:var(--paper);border-bottom:1px solid var(--line);display:grid;gap:16px;grid-template-columns:auto minmax(180px,1fr) auto;min-height:64px;padding:0 18px;position:sticky;top:0;z-index:10}.brand{align-items:center;display:flex;gap:10px}.brand-mark{background:#18211d;color:#fff;display:grid;font-weight:850;height:34px;place-items:center;position:relative;width:34px}.brand-mark:after{background:var(--red);bottom:-3px;content:"";height:9px;position:absolute;right:-3px;width:9px}.brand strong{font-size:17px}.room-title{min-width:0}.room-title strong,.room-title span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.room-title strong{font-size:13px}.room-title span{color:var(--ink-soft);font-size:10px;margin-top:2px}.top-actions{align-items:center;display:flex;gap:7px}.live-pill{align-items:center;color:var(--ink-soft);display:flex;font-size:10px;gap:7px;white-space:nowrap}.live-dot{background:var(--green);border-radius:50%;box-shadow:0 0 0 4px rgba(22,130,93,.1);height:7px;width:7px}
    .button,.icon-button{align-items:center;background:var(--paper);border:1px solid var(--line);border-radius:4px;color:inherit;display:inline-flex;justify-content:center}.button{font-size:12px;font-weight:700;gap:6px;min-height:34px;padding:0 11px}.button.primary{background:#18211d;border-color:#18211d;color:#fff}.button:hover,.icon-button:hover{border-color:#96a39b}.icon-button{font-size:17px;height:32px;padding:0;width:32px}
    .shell{display:grid;grid-template-columns:minmax(225px,260px) minmax(420px,1fr) minmax(310px,365px);margin:0 auto;max-width:1940px;min-height:calc(100vh - 64px)}.shell.conductor-collapsed{grid-template-columns:minmax(225px,260px) minmax(420px,1fr)}.shell.preview-open{grid-template-columns:minmax(225px,260px) minmax(380px,1fr) minmax(320px,460px)}.team,.conductor,.preview-pane{background:var(--paper);height:calc(100vh - 64px);position:sticky;top:64px}.team{border-right:1px solid var(--line);display:flex;flex-direction:column}.conductor,.preview-pane{border-left:1px solid var(--line);min-width:0}.conductor{display:grid;grid-template-rows:auto auto minmax(100px,1fr) auto auto}.preview-pane{display:none;grid-template-rows:auto minmax(0,1fr)}.shell.preview-open .conductor{display:none}.shell.preview-open .preview-pane{display:grid}.shell.conductor-collapsed .conductor{display:none}
    .panel-heading{align-items:center;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;min-height:66px;padding:12px 14px}.eyebrow{color:var(--ink-soft);display:block;font-size:9px;font-weight:700;text-transform:uppercase}.panel-heading h2{font-size:15px;margin-top:3px}.conductor-seat{align-items:center;background:#e6eee8;border-bottom:1px solid var(--line);display:grid;gap:9px;grid-template-columns:auto 1fr auto;padding:11px 14px}.avatar{align-items:center;background:var(--role,#16825d);border-radius:50%;color:#fff;display:flex;flex:0 0 auto;font-size:10px;font-weight:800;height:31px;justify-content:center;width:31px}.conductor-seat .avatar{background:#18211d}.seat-copy{display:grid;min-width:0}.seat-copy strong{font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.seat-copy span{color:var(--ink-soft);font-size:9px;margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.presence{background:#a5aea9;border-radius:50%;height:7px;width:7px}.presence.on{background:var(--green);box-shadow:0 0 0 3px rgba(22,130,93,.1)}.people{flex:1;overflow:auto}.person{align-items:center;background:transparent;border:0;border-bottom:1px solid var(--line);border-left:3px solid var(--role,#16825d);display:grid;gap:8px;grid-template-columns:auto minmax(0,1fr) auto;padding:10px 9px;text-align:left;width:100%}.person:hover,.person.selected{background:#eef3ee}.person.pending{background:#f5f7f3;border-left-style:dashed}.person.pending .avatar{background:#78877e}.person button.seat-copy{background:transparent;border:0;padding:0;text-align:left}.person-actions{display:flex;gap:3px}.person-actions .icon-button{font-size:13px;height:25px;width:25px}.policy{background:#e4ebe5;color:#526059;display:inline-block;font-size:8px;margin-top:5px;padding:2px 4px;width:max-content}.team-empty{background:transparent;border:0;color:inherit;display:grid;gap:4px;padding:18px 14px;text-align:left;width:100%}.team-empty strong{font-size:11px}.team-empty span{color:var(--ink-soft);font-size:9px;line-height:1.45}
    .stage{min-width:0;padding:18px}.stage-heading{align-items:flex-start;display:flex;gap:16px;justify-content:space-between;margin-bottom:14px}.stage-heading h1{font-size:27px;line-height:1.05;margin-top:5px}.stage-heading p{color:var(--ink-soft);font-size:10px;margin-top:7px}.lane-state{align-items:center;background:var(--paper);border:1px solid var(--line);display:flex;gap:8px;padding:7px 9px;white-space:nowrap}.lane-state .presence{background:var(--yellow)}.lane-state .presence.on{background:var(--green)}.lane-stats{border-left:1px solid var(--line);color:var(--ink-soft);font-size:8px;padding-left:8px}
    .terminal{background:var(--terminal);border:1px solid #111613;box-shadow:9px 9px 0 rgba(25,33,30,.1);color:var(--terminal-copy);min-height:470px;overflow:hidden}.terminal-bar{align-items:center;background:#222b26;border-bottom:1px solid var(--terminal-line);display:grid;gap:10px;grid-template-columns:auto minmax(0,1fr) auto auto;padding:8px 10px}.traffic{display:flex;gap:5px}.traffic i{background:#617068;border-radius:50%;height:7px;width:7px}.traffic i:first-child{background:var(--red)}.traffic i:nth-child(2){background:var(--yellow)}.traffic i:last-child{background:var(--green)}.terminal-title{color:#aebdb3;font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.terminal-meta{color:#819188;font-size:8px}.terminal-modes{background:#151b18;border:1px solid #354239;display:flex;gap:2px;padding:2px}.mode-button{background:transparent;border:0;color:#819188;font-size:8px;font-weight:800;height:22px;padding:0 7px;text-transform:uppercase}.mode-button.active{background:#344139;color:#eff6f0}.terminal-view{display:none;height:min(66vh,680px);min-height:420px}.terminal-view.active{display:block}.terminal-live{contain:layout paint;max-width:100%;overflow:auto;padding:7px}.ghostty-terminal{height:100%;max-width:100%;min-height:406px;min-width:0;outline:none;width:100%}.ghostty-terminal canvas{display:block}.terminal-stream{overflow:auto;padding:8px 0 28px}.terminal-empty{align-items:center;color:#78877e;display:flex;font-size:11px;justify-content:center;min-height:390px;padding:35px;text-align:center}.event{border-bottom:1px solid rgba(255,255,255,.035);display:grid;gap:10px;grid-template-columns:62px 116px minmax(0,1fr);padding:8px 12px}.event:hover{background:rgba(255,255,255,.025)}.event-time{color:#738179;font-size:8px}.event-kind{color:#84a490;font-size:8px;overflow-wrap:anywhere}.event-copy{color:#d3ded6;font-size:11px;line-height:1.5;overflow-wrap:anywhere;white-space:pre-wrap}.cursor-line{align-items:center;color:#91a198;display:flex;font:10px "SFMono-Regular",Consolas,monospace;gap:8px;padding:12px}.cursor{animation:blink 1s steps(1,end) infinite;background:#72bd93;height:13px;width:7px}@keyframes blink{50%{opacity:0}}
    .form{border-bottom:1px solid var(--line);display:grid;gap:7px;padding:11px}.command-grid{display:grid;gap:6px;grid-template-columns:1fr 1fr}.field,input,select,textarea{background:#fff;border:1px solid var(--line);border-radius:4px;color:inherit;min-width:0;outline:none}.field,input,select{height:36px;padding:0 9px}textarea{min-height:76px;padding:8px 9px;resize:vertical}input:focus,select:focus,textarea:focus{border-color:var(--blue);box-shadow:0 0 0 2px rgba(50,103,214,.12)}.form input,.form select,.form textarea{font-size:11px}.form .button{width:100%}.messages{overflow:auto;padding:8px 12px}.message{border-bottom:1px solid #e6eae5;padding:11px 3px}.message.conductor-message{background:#eaf1eb;border-left:3px solid var(--green);margin:5px -4px;padding:11px 8px}.message strong{font-size:9px;text-transform:uppercase}.message p{font-size:11px;line-height:1.45;margin-top:4px;white-space:pre-wrap}.message time{color:var(--ink-soft);font-size:8px;margin-left:5px}.connection{border-top:1px solid var(--line);color:var(--ink-soft);font-size:9px;padding:9px 12px}
    .preview-toolbar{align-items:center;background:var(--soft);border-bottom:1px solid var(--line);display:grid;gap:7px;grid-template-columns:minmax(0,1fr) auto;padding:9px 11px}.preview-copy{min-width:0}.preview-copy strong,.preview-copy span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.preview-copy strong{font-size:11px}.preview-copy span{color:var(--ink-soft);font-size:8px;margin-top:3px}.preview-actions{display:flex;gap:4px}.preview-frame{border:0;height:100%;min-height:0;width:100%}
    dialog{background:var(--paper);border:1px solid #aeb9af;box-shadow:12px 12px 0 rgba(24,33,29,.14);color:inherit;max-width:510px;padding:0;width:calc(100% - 28px)}dialog::backdrop{background:rgba(24,33,29,.38)}.dialog-body{display:grid;gap:12px;padding:15px}.dialog-fields{display:grid;gap:8px;grid-template-columns:1fr 1fr}.check{align-items:center;color:#526059;display:flex;font-size:10px;gap:7px}.check input{accent-color:var(--green);height:14px;margin:0;width:14px}.command-preview{background:#19211e;border:0;border-radius:4px;color:#d9e4dc;font:10px/1.45 "SFMono-Regular",Consolas,monospace;min-height:82px;padding:9px;width:100%}.dialog-actions{display:flex;gap:7px;justify-content:flex-end}.toast{background:#18211d;bottom:16px;color:#fff;font-size:11px;left:50%;opacity:0;padding:9px 12px;pointer-events:none;position:fixed;transform:translate(-50%,10px);transition:opacity .15s ease,transform .15s ease;z-index:30}.toast.show{opacity:1;transform:translate(-50%,0)}
    @media(max-width:1120px){.shell,.shell.preview-open{grid-template-columns:230px minmax(0,1fr)}.conductor,.preview-pane{border-left:0;border-top:1px solid var(--line);grid-column:1/-1;height:auto;position:static}.shell:not(.conductor-collapsed):not(.preview-open) .conductor{display:grid}.shell.preview-open .preview-pane{display:grid;height:65vh}.messages{max-height:320px}.terminal-view{height:58vh}}@media(max-width:740px){.topbar{gap:9px;grid-template-columns:auto 1fr;padding:0 10px}.brand strong,.top-actions .button{display:none}.shell,.shell.conductor-collapsed,.shell.preview-open{display:block}.team,.conductor,.preview-pane{height:auto;position:static}.team{border-right:0}.people{max-height:300px}.stage{padding:13px 10px}.stage-heading{align-items:flex-start;display:grid}.lane-state{margin-top:4px;width:max-content}.lane-stats{font-size:7px}.terminal{box-shadow:none}.terminal-bar{grid-template-columns:auto minmax(0,1fr) auto}.terminal-meta{display:none}.terminal-view{height:60vh;min-height:360px}.ghostty-terminal{min-height:346px}.event{gap:5px;grid-template-columns:48px 88px minmax(0,1fr);padding:7px 8px}.command-grid,.dialog-fields{grid-template-columns:1fr}.top-actions{justify-self:end}.live-pill{display:none}.shell.conductor-collapsed .conductor{display:none}.shell.preview-open .preview-pane{display:grid;height:62vh}.preview-pane{display:none}}
  </style>
  <script type="importmap">{"imports":{"ghostty-web":"${GHOSTTY_ASSET_PATHS.module}"}}</script>
</head>
<body>
  <header class="topbar">
    <div class="brand"><span class="brand-mark">M</span><strong>multicodex</strong></div>
    <div class="room-title"><strong id="room-title">loading room</strong><span id="room-meta">connecting to host-local room</span></div>
    <div class="top-actions"><span class="live-pill"><i class="live-dot"></i><span id="top-status">connecting</span></span><button class="button" id="open-invite">invite teammate</button><button class="icon-button" id="toggle-conductor" title="hide conductor controls">x</button></div>
  </header>
  <div class="shell" id="shell">
    <aside class="team">
      <div class="panel-heading"><div><span class="eyebrow">team</span><h2 id="seat-count">0 active - 0 invited</h2></div><button class="icon-button" id="open-invite-quick" title="invite teammate">+</button></div>
      <div class="conductor-seat"><span class="avatar">AI</span><div class="seat-copy"><strong>conductor</strong><span>host-local coordination</span></div><i class="presence on"></i></div>
      <div class="people" id="people"></div>
    </aside>
    <main class="stage">
      <div class="stage-heading"><div><span class="eyebrow">live lane</span><h1 id="lane-title">waiting for a builder</h1><p id="lane-detail">create a named invite to connect a normal local Codex TUI.</p></div><div class="lane-state"><i class="presence" id="lane-presence"></i><span class="status" id="lane-state">idle</span><span class="lane-stats mono" id="lane-stats">0 lanes · 0 turns · 0 actions</span></div></div>
      <section class="terminal">
        <div class="terminal-bar"><span class="traffic"><i></i><i></i><i></i></span><span class="terminal-title" id="terminal-title">multicodex://room/lane</span><span class="terminal-meta" id="terminal-meta">structured activity</span><span class="terminal-modes"><button class="mode-button active" id="mode-live" type="button">live</button><button class="mode-button" id="mode-activity" type="button">activity</button><button class="mode-button" id="mode-preview" type="button">preview</button></span></div>
        <div class="terminal-view terminal-live active" id="terminal-live"><div class="ghostty-terminal" id="ghostty-terminal"></div></div>
        <div class="terminal-view terminal-stream" id="terminal-stream"></div>
      </section>
    </main>
    <aside class="conductor" id="conductor">
      <div class="panel-heading"><div><span class="eyebrow">conductor</span><h2>lane control</h2></div><button class="icon-button" id="collapse-conductor" title="hide conductor controls">x</button></div>
      <form class="form" id="command-form"><span class="eyebrow">selected lane</span><div class="command-grid"><select name="laneId" id="lane-select" required></select><select name="kind" id="kind-select"><option value="suggest">suggest</option><option value="request_status">request status</option><option value="start_followup">start work</option><option value="steer_active_turn">steer active turn</option><option value="request_interrupt">interrupt active turn</option></select></div><textarea name="text" id="command-text" placeholder="what should the lane know or do?" required maxlength="2000"></textarea><button class="button primary" id="action-button">send action</button></form>
      <div class="messages" id="messages"></div>
      <form class="form" id="message-form"><input name="text" placeholder="message the conductor" required maxlength="2000"><button class="button">send room message</button></form>
      <div class="connection status" id="connection">connecting...</div>
    </aside>
    <aside class="preview-pane" id="preview-pane">
      <div class="preview-toolbar"><div class="preview-copy"><strong id="preview-title">lane preview</strong><span id="preview-url"></span></div><div class="preview-actions"><button class="icon-button" id="refresh-preview" title="refresh preview">r</button><a class="icon-button" id="open-preview-external" title="open preview in a new tab" target="_blank" rel="noopener">o</a><button class="icon-button" id="close-preview" title="close preview">x</button></div></div>
      <iframe class="preview-frame" id="preview-frame" title="lane preview" sandbox="allow-scripts allow-forms allow-modals allow-popups allow-same-origin"></iframe>
    </aside>
  </div>
  <dialog id="invite-dialog">
    <form class="dialog-body" id="invite-form">
      <div class="panel-heading"><div><span class="eyebrow">invite teammate</span><h2>create a lane invite</h2></div><button class="icon-button" id="close-invite" type="button" title="close invite dialog">x</button></div>
      <div class="dialog-fields"><label><span class="eyebrow">name</span><input id="invite-name" name="name" placeholder="teammate name" required maxlength="80"></label><label><span class="eyebrow">policy</span><select name="policy"><option value="suggest">suggest</option><option value="steer">steer</option><option value="observe">observe</option></select></label></div>
      <label class="check"><input id="invite-mirror" name="terminalMirror" type="checkbox" checked><span>share live terminal mirror</span></label>
      <label class="check"><input id="invite-control" name="terminalControl" type="checkbox"><span>allow host terminal control</span></label>
      <div><span class="eyebrow">join command</span><textarea class="command-preview" id="invite-command" readonly></textarea></div>
      <div class="dialog-actions"><button class="button" id="copy-invite-command" type="button">copy command</button><button class="button primary" id="create-invite">create &amp; copy invite</button></div>
    </form>
  </dialog>
  <div class="toast" id="toast"></div>
  <script>
    const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const ui={shell:document.querySelector('#shell'),roomTitle:document.querySelector('#room-title'),roomMeta:document.querySelector('#room-meta'),topStatus:document.querySelector('#top-status'),seatCount:document.querySelector('#seat-count'),people:document.querySelector('#people'),laneTitle:document.querySelector('#lane-title'),laneDetail:document.querySelector('#lane-detail'),lanePresence:document.querySelector('#lane-presence'),laneState:document.querySelector('#lane-state'),laneStats:document.querySelector('#lane-stats'),terminalTitle:document.querySelector('#terminal-title'),terminalMeta:document.querySelector('#terminal-meta'),terminalLive:document.querySelector('#terminal-live'),ghosttyTerminal:document.querySelector('#ghostty-terminal'),terminalStream:document.querySelector('#terminal-stream'),modeLive:document.querySelector('#mode-live'),modeActivity:document.querySelector('#mode-activity'),modePreview:document.querySelector('#mode-preview'),messages:document.querySelector('#messages'),laneSelect:document.querySelector('#lane-select'),kindSelect:document.querySelector('#kind-select'),commandText:document.querySelector('#command-text'),actionButton:document.querySelector('#action-button'),connection:document.querySelector('#connection'),toast:document.querySelector('#toast'),inviteDialog:document.querySelector('#invite-dialog'),inviteForm:document.querySelector('#invite-form'),inviteName:document.querySelector('#invite-name'),inviteMirror:document.querySelector('#invite-mirror'),inviteControl:document.querySelector('#invite-control'),inviteCommand:document.querySelector('#invite-command'),previewPane:document.querySelector('#preview-pane'),previewTitle:document.querySelector('#preview-title'),previewUrl:document.querySelector('#preview-url'),previewFrame:document.querySelector('#preview-frame'),previewExternal:document.querySelector('#open-preview-external')};
    const roleColors=['#dd503c','#3267d6','#16825d','#d59b18','#835bb5'];
    const fragment=new URLSearchParams(location.hash.replace(/^#/,''));const hostToken=fragment.get('host')||sessionStorage.getItem('multicodex-host-token')||'';const laneToken=fragment.get('token')||sessionStorage.getItem('multicodex-lane-token')||'';const viewerLaneId=fragment.get('lane')||sessionStorage.getItem('multicodex-lane-id')||'';
    if(hostToken)sessionStorage.setItem('multicodex-host-token',hostToken);if(laneToken)sessionStorage.setItem('multicodex-lane-token',laneToken);if(viewerLaneId)sessionStorage.setItem('multicodex-lane-id',viewerLaneId);
    let snapshot=null,hostConfig=null,selectedLaneId='',refreshing=false,terminalMode='live',terminalSession=null,terminalGeneration=0,libterminalBrowserPromise=null,terminalInputQueue=Promise.resolve(),previewLaneId='',conductorCollapsed=sessionStorage.getItem('multicodex-conductor-collapsed')==='true';
    async function api(path,options={}){const headers={...(options.body?{'content-type':'application/json'}:{}),...(options.host&&hostToken?{authorization:'Bearer '+hostToken}:{}),...(options.lane&&laneToken?{authorization:'Bearer '+laneToken}:{})};const response=await fetch(path,{method:options.method||'GET',headers,body:options.body?JSON.stringify(options.body):undefined});const payload=await response.json();if(!response.ok)throw new Error(payload.error||response.statusText);return payload}
    function initials(name){return String(name||'?').split(/\\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}function time(at){return new Date(at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}function shellQuote(value){const q=String.fromCharCode(39),d=String.fromCharCode(34);return q+String(value).replaceAll(q,q+d+q+d+q)+q}function toast(message){ui.toast.textContent=message;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1700)}async function copy(value,message='copied'){if(!value)throw new Error('nothing to copy yet');await navigator.clipboard.writeText(value);toast(message)}
    function activeLanes(){return snapshot?snapshot.lanes.filter(lane=>!lane.removedAt):[]}function pendingInvites(){return snapshot?snapshot.invites.filter(invite=>!invite.claimedAt&&!invite.revokedAt):[]}function selectedLane(){const lanes=activeLanes();return lanes.find(lane=>lane.id===selectedLaneId)||lanes[0]||snapshot?.lanes[0]||null}function laneEvents(laneId){return (snapshot?.events||[]).filter(event=>event.laneId===laneId).slice(-100)}function eventClass(kind){return kind.replaceAll('.','-')}function terminalToken(){return hostToken||laneToken}function canTerminalControl(lane){return Boolean(hostToken&&lane?.terminalControl&&lane?.terminalMirror&&lane?.connected)}
    async function sendTerminalInput(laneId,bytes){try{const response=await roomFetch('/api/lanes/'+encodeURIComponent(laneId)+'/terminal-input',{method:'POST',headers:{authorization:'Bearer '+hostToken,'content-type':'application/octet-stream'},body:bytes});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||'terminal control unavailable')}}catch(error){toast(error.message||'terminal control unavailable')}}function queueTerminalInput(laneId,bytes){const input=bytes.slice();terminalInputQueue=terminalInputQueue.then(()=>sendTerminalInput(laneId,input)).catch(()=>undefined)}
    function stopLiveTerminal(){terminalGeneration+=1;terminalSession?.controller?.abort();try{terminalSession?.terminal?.dispose?.()}catch{}terminalSession=null;ui.ghosttyTerminal.innerHTML=''}function terminalEmpty(message){ui.ghosttyTerminal.innerHTML='<div class="terminal-empty">'+esc(message)+'</div>'}async function libterminalBrowser(){libterminalBrowserPromise||=import('/vendor/libterminal/browser.js');return libterminalBrowserPromise}
    const roomFetch=window.fetch.bind(window);window.fetch=async(input,options)=>{const response=await roomFetch(input,options);const href=typeof input==='string'?input:input instanceof URL?input.href:input.url;const method=options?.method||(input instanceof Request?input.method:'GET');if(response.ok&&method.toUpperCase()==='GET'&&/^\\/api\\/lanes\\/[^\\/]+\\/terminal$/.test(new URL(href,location.href).pathname)&&response.body){const module=await import('/vendor/multicodex-terminal-stream.js');return new Response(module.terminalEventBytes(response.body),{status:response.status,statusText:response.statusText,headers:response.headers})}return response};
    async function connectLiveTerminal(lane){const control=canTerminalControl(lane);if(terminalSession?.laneId===lane.id){terminalSession.terminal?.setReadOnly(!control);terminalSession.control=control;return}stopLiveTerminal();const generation=terminalGeneration;const controller=new AbortController();terminalSession={laneId:lane.id,controller,terminal:null,control};terminalEmpty(control?'connecting terminal control...':'connecting read-only terminal mirror...');try{const module=await libterminalBrowser();if(generation!==terminalGeneration)return;ui.ghosttyTerminal.innerHTML='';const columns=lane.terminalColumns||120,rows=lane.terminalRows||34;const terminal=await module.createGhosttyTerminal({parent:ui.ghosttyTerminal,runtimeOptions:{wasmUrl:'${GHOSTTY_ASSET_PATHS.wasm}'},readOnly:!control,autoFit:true,signal:controller.signal,onData:bytes=>{if(control)queueTerminalInput(lane.id,bytes)},terminalOptions:{fontSize:13,theme:{background:'#171d1a',foreground:'#d9e4dc',cursor:'#72bd93',selectionBackground:'#435047',black:'#171d1a',red:'#ed7868',green:'#72bd93',yellow:'#ddb85c',blue:'#77a8ee',magenta:'#b89bd6',cyan:'#73b7ad',white:'#d9e4dc',brightBlack:'#78877e',brightRed:'#f29b8f',brightGreen:'#9bd2ae',brightYellow:'#ead18d',brightBlue:'#a1c2ef',brightMagenta:'#ccb8df',brightCyan:'#9dd0c8',brightWhite:'#f1f6f2'}}});terminalSession={laneId:lane.id,controller,terminal,columns,rows,control};const response=await fetch('/api/lanes/'+encodeURIComponent(lane.id)+'/terminal',{headers:{authorization:'Bearer '+terminalToken()},signal:controller.signal});if(!response.ok)throw new Error('mirror unavailable ('+response.status+')');if(!response.body)throw new Error('mirror stream unavailable');ui.terminalMeta.textContent=control?'live terminal - host control':'live mirror - read-only';await terminal.attach(response.body,controller.signal);if(generation===terminalGeneration)ui.terminalMeta.textContent='live mirror ended'}catch(error){if(generation!==terminalGeneration||error.name==='AbortError')return;terminalEmpty(error.message||'live terminal unavailable');ui.terminalMeta.textContent='structured activity available'}}
    function syncTerminalMode(lane){const canLive=Boolean(activeLanes().some(candidate=>candidate.terminalMirror&&(hostToken||laneToken)));const live=terminalMode==='live'&&Boolean(lane?.terminalMirror)&&canLive;ui.modeLive.disabled=!canLive;ui.modeLive.classList.toggle('active',live);ui.modeActivity.classList.toggle('active',!live);ui.terminalLive.classList.toggle('active',live);ui.terminalStream.classList.toggle('active',!live);if(live){void connectLiveTerminal(lane)}else stopLiveTerminal()}
    function renderPeople(){const active=activeLanes(),pending=pendingInvites();ui.seatCount.textContent=active.length+' active - '+pending.length+' invited';const people=active.map((lane,index)=>'<div class="person '+(lane.id===selectedLaneId?'selected ':'')+'" style="--role:'+roleColors[index%roleColors.length]+'"><span class="avatar">'+esc(initials(lane.displayName))+'</span><button class="seat-copy" data-select="'+esc(lane.id)+'"><strong>'+esc(lane.displayName)+'</strong><span>'+esc(lane.connected?lane.status:'offline - '+lane.status)+'</span><i class="policy">'+esc(lane.policy)+'</i></button><span class="person-actions">'+(hostToken?'<button class="icon-button" data-remove="'+esc(lane.id)+'" title="remove '+esc(lane.displayName)+'">x</button>':'')+'</span></div>').join('');const invites=pending.map(invite=>'<div class="person pending"><span class="avatar">+</span><div class="seat-copy"><strong>'+esc(invite.displayName)+'</strong><span>invite ready - waiting to join</span><i class="policy">'+esc(invite.policy)+(invite.terminalMirror?' - terminal':'')+'</i></div><span class="person-actions">'+(hostToken?'<button class="icon-button" data-copy-invite="'+esc(invite.id)+'" title="copy invite for '+esc(invite.displayName)+'">c</button><button class="icon-button" data-revoke-invite="'+esc(invite.id)+'" title="revoke invite for '+esc(invite.displayName)+'">x</button>':'')+'</span></div>').join('');ui.people.innerHTML=people+invites||(hostToken?'<button class="team-empty" data-open-invite><strong>invite the first teammate</strong><span>create a named command for their own local repo</span></button>':'<div class="team-empty"><strong>waiting for teammates</strong><span>the host has not invited anyone yet</span></div>');ui.people.querySelectorAll('[data-select]').forEach(button=>button.onclick=()=>{selectedLaneId=button.dataset.select;render()});ui.people.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>removeLane(button.dataset.remove));ui.people.querySelectorAll('[data-copy-invite]').forEach(button=>button.onclick=()=>copy(inviteCommand(button.dataset.copyInvite),'invite copied'));ui.people.querySelectorAll('[data-revoke-invite]').forEach(button=>button.onclick=()=>revokeInvite(button.dataset.revokeInvite));ui.people.querySelector('[data-open-invite]')?.addEventListener('click',openInvite)}
    function renderTerminal(){const lane=selectedLane();if(!lane){ui.laneTitle.textContent='waiting for a builder';ui.laneDetail.textContent='create a named invite to connect a normal local Codex TUI.';ui.laneState.textContent='idle';ui.lanePresence.className='presence';ui.terminalMeta.textContent='structured activity';ui.terminalStream.innerHTML='<div class="terminal-empty">no lane selected<br>the real Codex terminal stays on each participant machine.</div>';syncTerminalMode(null);return}selectedLaneId=lane.id;ui.laneTitle.textContent=lane.displayName;ui.laneDetail.textContent=lane.repo+' - '+lane.policy+' policy - '+(lane.threadId?'thread '+lane.threadId:'thread pending')+(lane.terminalMirror?' - terminal mirrored':'')+(lane.terminalControl?' - host control enabled':'');ui.laneState.textContent=lane.removedAt?'removed':lane.currentTurnId?'active turn':lane.connected?'connected':'disconnected';ui.lanePresence.className='presence '+(lane.connected&&!lane.removedAt?'on':'');ui.terminalTitle.textContent='multicodex://'+snapshot.id+'/'+lane.displayName.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-');ui.terminalMeta.textContent=lane.terminalMirror?(canTerminalControl(lane)?'live terminal - host control':'live mirror - read-only'):lane.policy+' - structured activity';const events=laneEvents(lane.id);ui.terminalStream.innerHTML=(events.length?events.map(event=>'<div class="event '+eventClass(event.kind)+'"><time class="event-time">'+time(event.at)+'</time><code class="event-kind">'+esc(event.kind.replaceAll('agent.','ai.'))+'</code><div class="event-copy">'+esc(event.summary)+'</div></div>').join(''):'<div class="terminal-empty">lane connected; waiting for meaningful Codex activity.</div>')+(lane.currentTurnId?'<div class="cursor-line"><span>&gt;</span><i class="cursor"></i><span>Codex turn in progress</span></div>':'');ui.terminalStream.scrollTop=ui.terminalStream.scrollHeight;syncTerminalMode(lane)}
    function renderMessages(){const messages=snapshot?.conductorMessages||[];ui.messages.innerHTML=messages.length?messages.slice(-80).map(message=>'<div class="message '+(message.author==='conductor'?'conductor-message':'')+'"><strong>'+esc(message.authorName||message.author)+'</strong><time>'+time(message.at)+'</time><p>'+esc(message.body)+'</p></div>').join(''):'<div class="terminal-empty">room messages and conductor replies appear here.</div>';ui.messages.scrollTop=ui.messages.scrollHeight}
    function syncCommandControls(){const lane=activeLanes().find(candidate=>candidate.id===ui.laneSelect.value);const active=Boolean(lane?.currentTurnId),rank={observe:0,suggest:1,steer:2},required={suggest:1,request_status:1,start_followup:2,steer_active_turn:2,request_interrupt:2};for(const option of ui.kindSelect.options){const kind=option.value;option.disabled=!lane||rank[lane.policy]<required[kind]||(!active&&['steer_active_turn','request_interrupt'].includes(kind))}if(ui.kindSelect.selectedOptions[0]?.disabled){const allowed=[...ui.kindSelect.options].find(option=>!option.disabled);ui.kindSelect.value=allowed?.value||''}const kind=ui.kindSelect.value,available=Boolean(kind);ui.kindSelect.disabled=!available;ui.commandText.disabled=!available;ui.actionButton.disabled=!available;ui.commandText.placeholder={suggest:'what should the lane know?',request_status:'what status do you need?',start_followup:'what should Codex do next?',steer_active_turn:'how should the active turn change?',request_interrupt:'why should the active turn stop?'}[kind]||'lane policy does not allow conductor actions';ui.actionButton.textContent={suggest:'send suggestion',request_status:'request status',start_followup:'start Codex turn',steer_active_turn:'steer active turn',request_interrupt:'interrupt active turn'}[kind]||'lane is observe-only'}
    function renderControls(){const lanes=activeLanes();const previous=ui.laneSelect.value||selectedLaneId;ui.laneSelect.innerHTML=lanes.map(lane=>'<option value="'+esc(lane.id)+'">'+esc(lane.displayName)+'</option>').join('');ui.laneSelect.value=lanes.some(lane=>lane.id===previous)?previous:(lanes[0]?.id||'');syncCommandControls();const hostLocked=!hostToken;document.querySelector('#command-form').hidden=hostLocked;document.querySelector('#open-invite').hidden=hostLocked;document.querySelector('#open-invite-quick').hidden=hostLocked;document.querySelectorAll('#message-form input,#message-form button').forEach(element=>element.disabled=!hostToken&&!laneToken);const mode=hostToken?'host':laneToken?'participant':'observer';ui.connection.textContent=(mode==='observer'?'read-only - ':'live - ')+new Date().toLocaleTimeString();ui.topStatus.textContent=mode==='host'?'host control':mode+' team view'}
    function renderStats(){const events=snapshot?.events||[];ui.laneStats.textContent=activeLanes().filter(lane=>lane.connected).length+' connected · '+events.filter(event=>event.kind==='turn.completed').length+' turns · '+events.filter(event=>event.kind==='command.result').length+' actions'}
    function setConductorCollapsed(value){conductorCollapsed=value;sessionStorage.setItem('multicodex-conductor-collapsed',String(value));ui.shell.classList.toggle('conductor-collapsed',value);document.querySelector('#toggle-conductor').title=value?'show conductor controls':'hide conductor controls'}function renderPreview(){const lane=activeLanes().find(candidate=>candidate.id===previewLaneId);if(!lane?.previewUrl){closePreview();return}ui.previewTitle.textContent=lane.displayName+' preview';ui.previewUrl.textContent=lane.previewUrl;ui.previewExternal.href=lane.previewUrl;if(ui.previewFrame.dataset.url!==lane.previewUrl){ui.previewFrame.dataset.url=lane.previewUrl;ui.previewFrame.src=lane.previewUrl}}
    function openPreview(){const lane=selectedLane();if(!lane?.previewUrl){toast('this lane has no attached preview');return}previewLaneId=lane.id;setConductorCollapsed(true);ui.shell.classList.add('preview-open');ui.modePreview.classList.add('active');renderPreview()}function closePreview(){previewLaneId='';ui.shell.classList.remove('preview-open');ui.modePreview.classList.remove('active');ui.previewFrame.removeAttribute('src');ui.previewFrame.dataset.url=''}
    function render(){if(!snapshot)return;ui.roomTitle.textContent=snapshot.title;ui.roomMeta.textContent=snapshot.repo+' - '+snapshot.id;renderPeople();renderTerminal();renderMessages();renderControls();renderStats();if(previewLaneId)renderPreview();setConductorCollapsed(conductorCollapsed)}
    async function refresh(){if(refreshing)return;refreshing=true;try{snapshot=await api('/api/snapshot');if(hostToken)hostConfig=await api('/api/host/config',{host:true});if(!selectedLaneId){const lanes=activeLanes();selectedLaneId=lanes.find(lane=>lane.currentTurnId&&lane.terminalMirror&&lane.connected)?.id||lanes.find(lane=>lane.terminalMirror&&lane.connected)?.id||lanes[0]?.id||''}render()}catch(error){ui.connection.textContent=error.message;ui.topStatus.textContent='offline'}finally{refreshing=false}}
    async function removeLane(laneId){const lane=snapshot.lanes.find(candidate=>candidate.id===laneId);if(!lane||!confirm('Remove '+lane.displayName+' and revoke this lane?'))return;await api('/api/lanes/'+encodeURIComponent(laneId),{method:'DELETE',host:true});toast(lane.displayName+' removed');await refresh()}function inviteCommand(inviteId){return hostConfig?.invites?.find(invite=>invite.id===inviteId)?.joinCommand||''}async function revokeInvite(inviteId){const invite=snapshot.invites.find(candidate=>candidate.id===inviteId);if(!invite||!confirm('Revoke the invite for '+invite.displayName+'?'))return;await api('/api/invites/'+encodeURIComponent(inviteId),{method:'DELETE',host:true});toast(invite.displayName+' invite revoked');await refresh()}
    function draftInviteCommand(){const data=new FormData(ui.inviteForm);const name=String(data.get('name')||'Builder');const policy=String(data.get('policy')||'suggest');const mirror=data.get('terminalMirror')==='on'?' --terminal-mirror':'';const control=data.get('terminalControl')==='on'?' --terminal-control':'';return 'npx --yes @vincentkoc/multicodex@latest join <invite-url> --repo . --name '+shellQuote(name)+' --policy '+policy+mirror+control}function updateInviteDraft(){if(!ui.inviteDialog.dataset.created)ui.inviteCommand.value=draftInviteCommand();ui.inviteControl.disabled=!ui.inviteMirror.checked;if(!ui.inviteMirror.checked)ui.inviteControl.checked=false}function openInvite(){if(!hostToken)return;ui.inviteDialog.dataset.created='';ui.inviteCommand.value=draftInviteCommand();updateInviteDraft();ui.inviteDialog.showModal();setTimeout(()=>ui.inviteName.focus(),0)}
    document.querySelector('#open-invite').onclick=openInvite;document.querySelector('#open-invite-quick').onclick=openInvite;document.querySelector('#close-invite').onclick=()=>ui.inviteDialog.close();document.querySelector('#copy-invite-command').onclick=()=>copy(ui.inviteCommand.value,'join command copied');ui.inviteName.oninput=updateInviteDraft;ui.inviteMirror.onchange=updateInviteDraft;ui.inviteControl.onchange=updateInviteDraft;ui.inviteForm.onsubmit=async event=>{event.preventDefault();const data=new FormData(ui.inviteForm);const name=String(data.get('name'));const created=await api('/api/invites',{method:'POST',host:true,body:{displayName:name,policy:data.get('policy'),terminalMirror:data.get('terminalMirror')==='on',terminalControl:data.get('terminalControl')==='on'}});ui.inviteDialog.dataset.created='true';ui.inviteCommand.value=created.joinCommand;await copy(created.joinCommand,'invite copied for '+name);toast('invite created and copied');await refresh()};
    document.querySelector('#message-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);const path=hostToken?'/api/conductor/message':'/api/lanes/'+encodeURIComponent(viewerLaneId)+'/message';const request=hostToken?{method:'POST',host:true,body:{text:data.get('text')}}:{method:'POST',lane:true,body:{text:data.get('text')}};await api(path,request);event.currentTarget.reset();toast('sent to room and conductor');await refresh()};document.querySelector('#command-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);await api('/api/conductor/command',{method:'POST',host:true,body:{laneId:data.get('laneId'),kind:data.get('kind'),text:data.get('text')}});ui.commandText.value='';toast('conductor action queued');await refresh()};ui.laneSelect.onchange=()=>{selectedLaneId=ui.laneSelect.value;syncCommandControls();render()};ui.kindSelect.onchange=syncCommandControls;ui.modeLive.onclick=()=>{if(!selectedLane()?.terminalMirror){const mirrored=activeLanes().find(lane=>lane.terminalMirror&&(hostToken||laneToken));if(mirrored)selectedLaneId=mirrored.id}terminalMode='live';render()};ui.modeActivity.onclick=()=>{terminalMode='activity';syncTerminalMode(selectedLane())};ui.modePreview.onclick=openPreview;document.querySelector('#refresh-preview').onclick=()=>{const url=ui.previewFrame.dataset.url;if(url)ui.previewFrame.src=url};document.querySelector('#close-preview').onclick=closePreview;document.querySelector('#toggle-conductor').onclick=()=>setConductorCollapsed(!conductorCollapsed);document.querySelector('#collapse-conductor').onclick=()=>setConductorCollapsed(true);
    setInterval(refresh,900);refresh();
  </script>
</body>
</html>`;
}
